/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.DAO_NhanVien;
import entity.NhanVien;

/**
 *
 * @author Lenovo
 */
public class EmployeeFrame extends javax.swing.JFrame {

	/**
	 * Creates new form EmployeeFrame
	 */
	String manv;
	int option = 0;

	public EmployeeFrame() throws ClassNotFoundException, SQLException {
		initComponents();
		setLocationRelativeTo(null);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws SQLException 
	 * @throws ClassNotFoundException 
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ClassNotFoundException, SQLException {

        jButton4 = new javax.swing.JButton();
        panelQuanLyNV = new javax.swing.JPanel();
        labelQLNV = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelMaNV = new javax.swing.JLabel();
        labelTenNV = new javax.swing.JLabel();
        labelSDT = new javax.swing.JLabel();
        labelChucVu = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelDiaChi = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        rdGioiTinh = new javax.swing.JRadioButton();
        labelMatkhau = new javax.swing.JLabel();
        labelLuong = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQLNV = new javax.swing.JTable();

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Thêm nhân viên");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        panelQuanLyNV.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelQuanLyNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelQLNV.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelQLNV.setText("QUẢN LÝ NHÂN VIÊN");

        labelMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaNV.setText("Mã nhân viên");

        labelTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenNV.setText("Tên nhân viên");

        labelSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSDT.setText("Số điện thoại");

        labelChucVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelChucVu.setText("Chức vụ");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEmail.setText("Email");

        labelDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDiaChi.setText("Địa chỉ");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnThoatActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnThemActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnXoaActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnLuu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnLuu1.setText("Lưu");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnLuu1ActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        rdGioiTinh.setText("Là Nam Giới");

        labelMatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMatkhau.setText("Mật khẩu");

        labelLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLuong.setText("Lương");

        javax.swing.GroupLayout panelQuanLyNVLayout = new javax.swing.GroupLayout(panelQuanLyNV);
        panelQuanLyNV.setLayout(panelQuanLyNVLayout);
        panelQuanLyNVLayout.setHorizontalGroup(
            panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(316, 316, 316)
                        .addComponent(labelQLNV)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMaNV)
                                    .addComponent(labelTenNV)
                                    .addComponent(labelSDT))
                                .addGap(18, 18, 18)
                                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelQuanLyNVLayout.createSequentialGroup()
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)
                                        .addComponent(labelChucVu))
                                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLyNVLayout.createSequentialGroup()
                                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(129, 129, 129)))
                                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDiaChi)
                                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMatkhau)
                                            .addComponent(labelLuong))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(rdGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(btnSua)
                                .addGap(153, 153, 153)
                                .addComponent(btnLuu1)))
                        .addGap(99, 99, 99)))
                .addContainerGap())
        );
        panelQuanLyNVLayout.setVerticalGroup(
            panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat)
                    .addComponent(labelQLNV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                        .addComponent(labelMaNV)
                        .addGap(27, 27, 27)
                        .addComponent(labelTenNV)
                        .addGap(35, 35, 35)
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSDT)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelQuanLyNVLayout.createSequentialGroup()
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChucVu)
                            .addComponent(rdGioiTinh))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(panelQuanLyNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnQuayLai)
                    .addComponent(btnLuu1))
                .addContainerGap())
        );

        tableQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Gioi Tinh", "Số điện thoại", "Chức vụ", "Lương", "Địa chỉ", "Mật khẩu", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQLNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQLNV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE)
            .addComponent(panelQuanLyNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLuu1.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        reset();
        pack();
        showThongTin();
    }// </editor-fold>//GEN-END:initComponents

	private void showThongTin() throws SQLException, ClassNotFoundException {
		DefaultTableModel tableModel = new DefaultTableModel(new Object[] { "Mã nhân viên", "Tên nhân viên",
				"Giới Tính","Số điện thoại", "Chức vụ","Lương", "Địa chỉ", "Mật khẩu", "Email" }, 0);
		ArrayList<NhanVien> dsnv;
		dsnv = new DAO_NhanVien().getDSNV();
		for (NhanVien nv : dsnv) {
			tableModel.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(),nv.getGioiTinh(), nv.getSodienthoai(), nv.getChucvu(),
					nv.getLuongcoban(),nv.getDiachi(), nv.getMatkhau(), nv.getEmail() });
		}
		tableQLNV.setModel(tableModel);
	}
	private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuayLaiActionPerformed
		// TODO add your handling code here:
		clearData();
		btnLuu1.setEnabled(false);
		btnThem.setEnabled(true);
		btnSua.setEnabled(false);
		btnXoa.setEnabled(false);
	}// GEN-LAST:event_btnQuayLaiActionPerformed

	private void clearData() {
		// TODO Auto-generated method stub
		txtChucVu.setText("");
		txtDiaChi.setText("");
		txtEmail.setText("");
		txtMaNV.setText("");
		txtSDT.setText("");
		txtTenNV.setText("");
		txtMatKhau.setText("");
		txtLuong.setText("");
		rdGioiTinh.setSelected(false);
		txtMaNV.requestFocus();
	}

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_btnXoaActionPerformed
		// TODO add your handling code here:
		String manv = txtMaNV.getText();
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa nhân viên!", "Warnning!",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			if (new DAO_NhanVien().delete(manv)) {
				JOptionPane.showMessageDialog(this, "Xóa thành công!");
				try {
					showThongTin();
					clearData();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else
				JOptionPane.showMessageDialog(this, "Xóa không thành công! Vui lòng xem lại!");
		}
		btnLuu1.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(true);
	}// GEN-LAST:event_btnXoaActionPerformed

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
		// TODO add your handling code here:

		txtChucVu.setEnabled(true);
		labelChucVu.setEnabled(true);
		txtDiaChi.setEnabled(true);
		labelDiaChi.setEnabled(true);
		txtEmail.setEnabled(true);
		labelEmail.setEnabled(true);
		txtMaNV.setEnabled(true);
		labelMaNV.setEnabled(true);
		txtSDT.setEnabled(true);
		labelSDT.setEnabled(true);
		txtTenNV.setEnabled(true);
		labelTenNV.setEnabled(true);
		txtLuong.setEnabled(true);
		txtMatKhau.setEnabled(true);
		rdGioiTinh.setEnabled(true);
		labelMatkhau.setEnabled(true);
		labelLuong.setEnabled(true);
		btnLuu1.setEnabled(true);
		btnXoa.setEnabled(false);
		btnThem.setEnabled(false);
		option = 2;
	}

	// GEN-LAST:event_btnSuaActionPerformed
	private void updateNV() throws ClassNotFoundException {
		NhanVien nv = revertNV();
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa nhân viên!", "Warnning!",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			if (new DAO_NhanVien().update(nv)) {
				JOptionPane.showMessageDialog(this, "Sửa thành công!");
				try {
					showThongTin();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				clearData();
			} else
				JOptionPane.showMessageDialog(this, "Sửa thất bại !Vui lòng xem  lại");
		}
	}

	private void insertNV() throws ClassNotFoundException {
		NhanVien nv = revertNV();
		String manv = txtMaNV.getText();
		String tennv = txtTenNV.getText();
		String sdt = txtSDT.getText();
		String chucvu = txtChucVu.getText();
		String diachi = txtDiaChi.getText();
		String email = txtEmail.getText();
		String luong=txtLuong.getText();
		String mk=txtMatKhau.getText();
		if (manv.equals("") || tennv.equals("") || sdt.equals("") || chucvu.equals("") || diachi.equals("")
				|| email.equals("")|| luong.equals("")||mk.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
			return;
		} else {
			if (new DAO_NhanVien().insert(nv)) {

				JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
				clearData();
				try {
					showThongTin();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else
				JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại! Vui lòng xem lại!");
		}
	}

	private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_btnLuuActionPerformed
		// TODO add your handling code here:
		if (option == 1) {
			insertNV();
            reset();
		} else if (option == 2) {
			updateNV();
			reset();
		}
		btnLuu1.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(true);

	}// GEN-LAST:event_btnLuuActionPerformed

	private void tableQLNVMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableQLNVMouseClicked
		// TODO add your handling code here:
		int click = tableQLNV.getSelectedRow();
		TableModel model = tableQLNV.getModel();
		txtMaNV.setText(model.getValueAt(click, 0).toString());
		txtTenNV.setText(model.getValueAt(click, 1).toString());
		rdGioiTinh.setSelected(Boolean.parseBoolean(model.getValueAt(click, 2).toString()));
		txtSDT.setText(model.getValueAt(click, 3).toString());
		txtChucVu.setText(model.getValueAt(click, 4).toString());
		txtLuong.setText( model.getValueAt(click, 5).toString());
		txtDiaChi.setText(model.getValueAt(click, 6).toString());
		txtMatKhau.setText(model.getValueAt(click, 7).toString());
		txtEmail.setText(model.getValueAt(click, 8).toString());
		btnThem.setEnabled(false);
		btnXoa.setEnabled(true);
		btnSua.setEnabled(true);

	}// GEN-LAST:event_tableQLNVMouseClicked

	private void btnThoatActionPerformed(ActionEvent evt) throws ClassNotFoundException {
		// TODO Auto-generated method stub
		dispose();
		new HomeFrame().setVisible(true);
	}


	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {// GEN-FIRST:event_btnThemActionPerformed
		// TODO add your handling code here:\?
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm nhân viên!", "Warnning!",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			txtChucVu.setEnabled(true);
			labelChucVu.setEnabled(true);
			txtDiaChi.setEnabled(true);
			labelDiaChi.setEnabled(true);
			txtEmail.setEnabled(true);
			labelEmail.setEnabled(true);
			txtMaNV.setEnabled(true);
			labelMaNV.setEnabled(true);
			txtSDT.setEnabled(true);
			labelSDT.setEnabled(true);
			txtTenNV.setEnabled(true);
			labelTenNV.setEnabled(true);
			txtLuong.setEnabled(true);
			txtMatKhau.setEnabled(true);
			rdGioiTinh.setEnabled(true);
			labelMatkhau.setEnabled(true);
			labelLuong.setEnabled(true);
			btnLuu1.setEnabled(true);
			btnXoa.setEnabled(false);
			btnSua.setEnabled(false);
			option = 1;
		}

	}// GEN-LAST:event_btnThemActionPerformed

	   private void reset() {
		   clearData();
		   txtChucVu.setEnabled(false); 
	        txtDiaChi.setEnabled(false); 
	        txtEmail.setEnabled(false); 
	        txtMaNV.setEnabled(false); 
	        txtSDT.setEnabled(false); 
	        txtTenNV.setEnabled(false); 
	        txtLuong.setEnabled(false);
	        rdGioiTinh.setEnabled(false);
	        txtMatKhau.setEnabled(false);
	   }


	private NhanVien revertNV() {
		// TODO Auto-generated method stub
		String manv = txtMaNV.getText();
		String tennv = txtTenNV.getText();
		String sdt = txtSDT.getText();
		String chucvu = txtChucVu.getText();
		String diachi = txtDiaChi.getText();
		String email = txtEmail.getText();
		double luong=Double.parseDouble(txtLuong.getText());
		String mk=txtMatKhau.getText();
		boolean phai=rdGioiTinh.isSelected();

		return new NhanVien(manv, tennv, phai, sdt, chucvu, luong, diachi, mk, email);
	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new EmployeeFrame().setVisible(true);
				} catch (ClassNotFoundException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelChucVu;
    private javax.swing.JLabel labelDiaChi;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLuong;
    private javax.swing.JLabel labelMaNV;
    private javax.swing.JLabel labelMatkhau;
    private javax.swing.JLabel labelQLNV;
    private javax.swing.JLabel labelSDT;
    private javax.swing.JLabel labelTenNV;
    private javax.swing.JPanel panelQuanLyNV;
    private javax.swing.JRadioButton rdGioiTinh;
    private javax.swing.JTable tableQLNV;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
