package gui;

import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.JFrame;

import dao.DAO_HomeFrame;

public class HomeFrame extends JFrame {
	DAO_HomeFrame daohome = new DAO_HomeFrame();
	LoginFrame login = new LoginFrame();

	public HomeFrame() throws ClassNotFoundException {

		initComponents();
		setLocationRelativeTo(null);
		phanquyen();
		new Thread() {
			public void run() {
				while (true) {
					Calendar ca = new GregorianCalendar();
					int hour = ca.get(Calendar.HOUR);
					int minute = ca.get(Calendar.MINUTE);
					int second = ca.get(Calendar.SECOND);
					int PM_AM = ca.get(Calendar.AM_PM);

					String day;
					if (PM_AM == 1) {
						day = "PM";
					} else {
						day = "AM";
					}
					String time = hour + ":" + minute + ":" + second + " " + day;
					labelDongHo.setText(time);
				}
			}
		}.start();
		try {
			labelvalueTenNV.setText(daohome.getTenNV(login.getMaNVText()));
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void phanquyen() throws ClassNotFoundException {
		String manv = new LoginFrame().getMaNVText();
		String chucvu = daohome.getChucVu(manv);
		if (chucvu.equals("NVBH")) {
			mnuItemDCHT.setEnabled(false);
			mnuItemLSP.setEnabled(false);
			mnuItemNCC.setEnabled(false);
			mnuItemNV.setEnabled(false);
			mnuItemSach.setEnabled(false);
			mnuItemThongKeDT.setEnabled(false);
			mnuItemThongKeSP.setEnabled(false);
			btnCapNhatLSP.setEnabled(false);
			btnCapNhatNCC.setEnabled(false);
			btnQuanLyDH.setEnabled(false);
			btnQuanLyNV.setEnabled(false);
			btnQuanLySP.setEnabled(false);
			btnThongKeDT.setEnabled(false);
			btnThongKeSP.setEnabled(false);
		}
		if (chucvu.equals("NVNK")) {
			mnuItemBanHang.setEnabled(false);
			mnuItemDatHang.setEnabled(false);
			mnuItemNV.setEnabled(false);
			mnuItemThongKeDT.setEnabled(false);
			mnuItemThongKeSP.setEnabled(false);
			btnBanHang.setEnabled(false);
			btnQuanLyDH.setEnabled(false);
			btnQuanLyNV.setEnabled(false);
			btnThongKeDT.setEnabled(false);
			btnThongKeSP.setEnabled(false);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton5 = new javax.swing.JButton();
		panelManHinhChinh = new javax.swing.JPanel();
		labelManHinhChinh = new javax.swing.JLabel();
		btnQuanLySP = new javax.swing.JButton();
		btnQuanLyDH = new javax.swing.JButton();
		btnDangXuat = new javax.swing.JButton();
		btnQuanLyNV = new javax.swing.JButton();
		btnBanHang = new javax.swing.JButton();
		btnThoat = new javax.swing.JButton();
		btnCapNhatNCC = new javax.swing.JButton();
		btnCapNhatLSP = new javax.swing.JButton();
		btnThongKeSP = new javax.swing.JButton();
		labelHoTenNV = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		btnThongKeDT = new javax.swing.JButton();
		panelDongHo = new javax.swing.JPanel();
		labelDongHo = new javax.swing.JLabel();
		btnChamCong = new javax.swing.JButton();
		labelvalueTenNV = new javax.swing.JLabel();
		menuBarHome = new javax.swing.JMenuBar();
		mnuDanhMuc = new javax.swing.JMenu();
		mnuItemDCHT = new javax.swing.JMenuItem();
		mnuItemNV = new javax.swing.JMenuItem();
		mnuItemLSP = new javax.swing.JMenuItem();
		mnuItemNCC = new javax.swing.JMenuItem();
		mnuItemSach = new javax.swing.JMenuItem();
		mnuTmKiem = new javax.swing.JMenu();
		mnuItemTKSach = new javax.swing.JMenuItem();
		mnuItemTKHD = new javax.swing.JMenuItem();
		mnuItemTKDH = new javax.swing.JMenuItem();
		mnuItemTKNCC = new javax.swing.JMenuItem();
		mnuitemTKLSP = new javax.swing.JMenuItem();
		mnuItemTKDDHT = new javax.swing.JMenuItem();
		mnuXuLy = new javax.swing.JMenu();
		mnuItemChamCong = new javax.swing.JMenuItem();
		mnuItemBanHang = new javax.swing.JMenuItem();
		mnuItemDoiMatKhau = new javax.swing.JMenuItem();
		mnuItemDatHang = new javax.swing.JMenuItem();
		mnuItemDangxuat = new javax.swing.JMenuItem();
		mnuThongKe = new javax.swing.JMenu();
		mnuItemThongKeSP = new javax.swing.JMenuItem();
		mnuItemThongKeDT = new javax.swing.JMenuItem();

		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money.png"))); // NOI18N
		jButton5.setText("Bán Hàng");
		jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Màn Hình Chính");
		setName("Màn"); // NOI18N

		panelManHinhChinh.setBackground(new java.awt.Color(204, 255, 204));
		panelManHinhChinh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		labelManHinhChinh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		labelManHinhChinh.setForeground(new java.awt.Color(102, 102, 102));
		labelManHinhChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bookstore.png"))); // NOI18N
		labelManHinhChinh.setText("QUẢN LÝ HIỆU SÁCH");

		btnQuanLySP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnQuanLySP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product.png"))); // NOI18N
		btnQuanLySP.setText("Quản lý sản phẩm");
		btnQuanLySP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnQuanLySP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnQuanLySP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuanLySPActionPerformed(evt);
			}
		});

		btnQuanLyDH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnQuanLyDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trolley.png"))); // NOI18N
		btnQuanLyDH.setText("Quản lý đơn hàng");
		btnQuanLyDH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnQuanLyDH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnQuanLyDH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuanLyDHActionPerformed(evt);
			}
		});

		btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
		btnDangXuat.setText("Đăng xuất");
		btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDangXuatActionPerformed(evt);
			}
		});

		btnQuanLyNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnQuanLyNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/best-employee.png"))); // NOI18N
		btnQuanLyNV.setText("Quản Lý nhân viên");
		btnQuanLyNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnQuanLyNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnQuanLyNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuanLyNVActionPerformed(evt);
			}
		});

		btnBanHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money.png"))); // NOI18N
		btnBanHang.setText("Bán Hàng");
		btnBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnBanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnBanHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBanHangActionPerformed(evt);
			}
		});

		btnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/multiply-1.png"))); // NOI18N
		btnThoat.setText("Thoát");
		btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnThoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThoatActionPerformed(evt);
			}
		});

		btnCapNhatNCC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnCapNhatNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/producer.png"))); // NOI18N
		btnCapNhatNCC.setText("Cập nhật nhà cung cấp");
		btnCapNhatNCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnCapNhatNCC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnCapNhatNCC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCapNhatNCCActionPerformed(evt);
			}
		});

		btnCapNhatLSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnCapNhatLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
		btnCapNhatLSP.setText("Cập nhật loại sản phẩm");
		btnCapNhatLSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnCapNhatLSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnCapNhatLSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCapNhatLSPActionPerformed(evt);
			}
		});

		btnThongKeSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnThongKeSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product-statistics.png"))); // NOI18N
		btnThongKeSP.setText("Thống kê sản phẩm");
		btnThongKeSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnThongKeSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnThongKeSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeSPActionPerformed(evt);
			}
		});

		labelHoTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		labelHoTenNV.setText("Nhân viên: ");

		btnThongKeDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnThongKeDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/analytics.png"))); // NOI18N
		btnThongKeDT.setText("Thống kê doanh thu");
		btnThongKeDT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnThongKeDT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnThongKeDT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeDTActionPerformed(evt);
			}
		});

		panelDongHo.setBackground(new java.awt.Color(153, 255, 153));

		labelDongHo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		labelDongHo.setForeground(new java.awt.Color(0, 0, 204));
		labelDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelDongHo.setText("7:40:00 AM");
		labelDongHo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		javax.swing.GroupLayout panelDongHoLayout = new javax.swing.GroupLayout(panelDongHo);
		panelDongHo.setLayout(panelDongHoLayout);
		panelDongHoLayout
				.setHorizontalGroup(panelDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelDongHoLayout.createSequentialGroup().addGap(53, 53, 53)
								.addComponent(labelDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
								.addContainerGap(48, Short.MAX_VALUE)));
		panelDongHoLayout.setVerticalGroup(
				panelDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						panelDongHoLayout.createSequentialGroup().addContainerGap()
								.addComponent(labelDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
								.addContainerGap()));

		btnChamCong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		btnChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/attendance.png"))); // NOI18N
		btnChamCong.setText("Chấm công");
		btnChamCong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChamCongActionPerformed(evt);
			}
		});

		labelvalueTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		labelvalueTenNV.setText("value tên nhân viên");

		javax.swing.GroupLayout panelManHinhChinhLayout = new javax.swing.GroupLayout(panelManHinhChinh);
		panelManHinhChinh.setLayout(panelManHinhChinhLayout);
		panelManHinhChinhLayout.setHorizontalGroup(panelManHinhChinhLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelManHinhChinhLayout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(panelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelManHinhChinhLayout.createSequentialGroup()
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(33, 33, 33)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(panelManHinhChinhLayout.createSequentialGroup()
														.addComponent(btnThongKeDT,
																javax.swing.GroupLayout.PREFERRED_SIZE, 229,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnThongKeSP,
																javax.swing.GroupLayout.PREFERRED_SIZE, 229,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(panelManHinhChinhLayout.createSequentialGroup()
														.addComponent(btnCapNhatNCC,
																javax.swing.GroupLayout.PREFERRED_SIZE, 229,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(50, 50, 50).addComponent(btnQuanLyDH,
																javax.swing.GroupLayout.PREFERRED_SIZE, 229,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(63, 63, 63)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnCapNhatLSP, javax.swing.GroupLayout.PREFERRED_SIZE,
														229, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(61, 61, 61)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnQuanLySP, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(panelManHinhChinhLayout.createSequentialGroup()
										.addComponent(labelManHinhChinh).addGap(271, 271, 271)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator1)
												.addGroup(panelManHinhChinhLayout.createSequentialGroup()
														.addGroup(panelManHinhChinhLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		panelManHinhChinhLayout.createSequentialGroup()
																				.addComponent(labelHoTenNV).addGap(28,
																						28, 28)
																				.addComponent(labelvalueTenNV))
																.addGroup(panelManHinhChinhLayout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(btnChamCong,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				189,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(panelDongHo,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGap(0, 22, Short.MAX_VALUE)))))
						.addGap(0, 8, Short.MAX_VALUE)));
		panelManHinhChinhLayout
				.setVerticalGroup(
						panelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManHinhChinhLayout
										.createSequentialGroup().addGap(19, 19, 19)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(labelManHinhChinh).addGroup(panelManHinhChinhLayout
														.createSequentialGroup().addGroup(panelManHinhChinhLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(labelHoTenNV)
																.addComponent(labelvalueTenNV))
														.addGap(18, 18, 18)
														.addComponent(
																jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(btnChamCong,
																javax.swing.GroupLayout.PREFERRED_SIZE, 53,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25,
												Short.MAX_VALUE)
										.addComponent(
												panelDongHo, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(69, 69, 69)
										.addGroup(panelManHinhChinhLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(panelManHinhChinhLayout.createSequentialGroup()
														.addGroup(panelManHinhChinhLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(btnBanHang,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 169,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		btnCapNhatNCC,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 169,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
												.addGroup(panelManHinhChinhLayout.createSequentialGroup()
														.addGap(0, 7, Short.MAX_VALUE).addGroup(panelManHinhChinhLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		false)
																.addGroup(panelManHinhChinhLayout
																		.createSequentialGroup().addComponent(
																				btnQuanLyDH,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				169,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(45, 45, 45).addComponent(btnThongKeSP,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				169,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(
																		btnQuanLyNV,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 169,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(panelManHinhChinhLayout
																		.createSequentialGroup()
																		.addGroup(panelManHinhChinhLayout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(btnCapNhatLSP,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						169,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(btnQuanLySP,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						169,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(45, 45, 45)
																		.addGroup(panelManHinhChinhLayout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(btnThoat,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						169,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(btnDangXuat,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						169,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addComponent(btnThongKeDT,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 169,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addContainerGap(29, Short.MAX_VALUE)))));

		mnuDanhMuc.setText("Danh mục");

		mnuItemDCHT.setText("Dụng cụ học tập");
		mnuItemDCHT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemDCHTActionPerformed(evt);
			}
		});
		mnuDanhMuc.add(mnuItemDCHT);

		mnuItemNV.setText("Nhân viên");
		mnuItemNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemNVActionPerformed(evt);
			}
		});
		mnuDanhMuc.add(mnuItemNV);

		mnuItemLSP.setText("Loại sản phẩm");
		mnuItemLSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemLSPActionPerformed(evt);
			}
		});
		mnuDanhMuc.add(mnuItemLSP);

		mnuItemNCC.setText("Nhà cung cấp");
		mnuItemNCC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemNCCActionPerformed(evt);
			}
		});
		mnuDanhMuc.add(mnuItemNCC);

		mnuItemSach.setText("Sách");
		mnuItemSach.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemSachActionPerformed(evt);
			}
		});
		mnuDanhMuc.add(mnuItemSach);

		menuBarHome.add(mnuDanhMuc);

		mnuTmKiem.setText("Tìm kiếm");

		mnuItemTKSach.setText("Tìm kiếm sách");
		mnuItemTKSach.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemTKSachActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuItemTKSach);

		mnuItemTKHD.setText("Tìm kiếm hóa đơn");
		mnuItemTKHD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemTKHDActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuItemTKHD);

		mnuItemTKDH.setText("Tìm kiếm đơn hàng");
		mnuItemTKDH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemTKDHActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuItemTKDH);

		mnuItemTKNCC.setText("Tìm kiếm nhà cung cấp");
		mnuItemTKNCC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemTKNCCActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuItemTKNCC);

		mnuitemTKLSP.setText("Tìm kiếm loại sản phẩm");
		mnuitemTKLSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuitemTKLSPActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuitemTKLSP);

		mnuItemTKDDHT.setText("Tìm kiếm đồ dùng học tập");
		mnuItemTKDDHT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemTKDDHTActionPerformed(evt);
			}
		});
		mnuTmKiem.add(mnuItemTKDDHT);

		menuBarHome.add(mnuTmKiem);

		mnuXuLy.setText("Xử lý");

		mnuItemChamCong.setText("Chấm công");
		mnuItemChamCong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemChamCongActionPerformed(evt);
			}
		});
		mnuXuLy.add(mnuItemChamCong);

		mnuItemBanHang.setText("Bán hàng");
		mnuItemBanHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemBanHangActionPerformed(evt);
			}
		});
		mnuXuLy.add(mnuItemBanHang);

		mnuItemDoiMatKhau.setText("Đổi mật khẩu");
		mnuItemDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemDoiMatKhauActionPerformed(evt);
			}
		});
		mnuXuLy.add(mnuItemDoiMatKhau);

		mnuItemDatHang.setText("Đặt hàng");
		mnuItemDatHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemDatHangActionPerformed(evt);
			}
		});
		mnuXuLy.add(mnuItemDatHang);

		mnuItemDangxuat.setText("Đăng xuất");
		mnuItemDangxuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemDangxuatActionPerformed(evt);
			}
		});
		mnuXuLy.add(mnuItemDangxuat);

		menuBarHome.add(mnuXuLy);

		mnuThongKe.setText("Thống kê");

		mnuItemThongKeSP.setText("Thống kê sản phẩm");
		mnuItemThongKeSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemThongKeSPActionPerformed(evt);
			}
		});
		mnuThongKe.add(mnuItemThongKeSP);

		mnuItemThongKeDT.setText("Thống kê doanh thu");
		mnuItemThongKeDT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuItemThongKeDTActionPerformed(evt);
			}
		});
		mnuThongKe.add(mnuItemThongKeDT);

		menuBarHome.add(mnuThongKe);

		setJMenuBar(menuBarHome);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(panelManHinhChinh,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(panelManHinhChinh, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		getAccessibleContext().setAccessibleDescription("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	protected void mnuItemThongKeDTActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemThongKeSPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemDangxuatActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemDatHangActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemDoiMatKhauActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemBanHangActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemChamCongActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemTKDDHTActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuitemTKLSPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemTKNCCActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemTKDHActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemTKHDActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemTKSachActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemSachActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemNCCActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemLSPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemNVActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void mnuItemDCHTActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnChamCongActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnThongKeDTActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnThongKeSPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnCapNhatLSPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnCapNhatNCCActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnThoatActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnBanHangActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnQuanLyNVActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnDangXuatActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnQuanLyDHActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void btnQuanLySPActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new HomeFrame().setVisible(true);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBanHang;
	private javax.swing.JButton btnCapNhatLSP;
	private javax.swing.JButton btnCapNhatNCC;
	private javax.swing.JButton btnChamCong;
	private javax.swing.JButton btnDangXuat;
	private javax.swing.JButton btnQuanLyDH;
	private javax.swing.JButton btnQuanLyNV;
	private javax.swing.JButton btnQuanLySP;
	private javax.swing.JButton btnThoat;
	private javax.swing.JButton btnThongKeDT;
	private javax.swing.JButton btnThongKeSP;
	private javax.swing.JButton jButton5;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JLabel labelDongHo;
	private javax.swing.JLabel labelHoTenNV;
	private javax.swing.JLabel labelManHinhChinh;
	private javax.swing.JLabel labelvalueTenNV;
	private javax.swing.JMenuBar menuBarHome;
	private javax.swing.JMenu mnuDanhMuc;
	private javax.swing.JMenuItem mnuItemBanHang;
	private javax.swing.JMenuItem mnuItemChamCong;
	private javax.swing.JMenuItem mnuItemDCHT;
	private javax.swing.JMenuItem mnuItemDangxuat;
	private javax.swing.JMenuItem mnuItemDatHang;
	private javax.swing.JMenuItem mnuItemDoiMatKhau;
	private javax.swing.JMenuItem mnuItemLSP;
	private javax.swing.JMenuItem mnuItemNCC;
	private javax.swing.JMenuItem mnuItemNV;
	private javax.swing.JMenuItem mnuItemSach;
	private javax.swing.JMenuItem mnuItemTKDDHT;
	private javax.swing.JMenuItem mnuItemTKDH;
	private javax.swing.JMenuItem mnuItemTKHD;
	private javax.swing.JMenuItem mnuItemTKNCC;
	private javax.swing.JMenuItem mnuItemTKSach;
	private javax.swing.JMenuItem mnuItemThongKeDT;
	private javax.swing.JMenuItem mnuItemThongKeSP;
	private javax.swing.JMenu mnuThongKe;
	private javax.swing.JMenu mnuTmKiem;
	private javax.swing.JMenu mnuXuLy;
	private javax.swing.JMenuItem mnuitemTKLSP;
	private javax.swing.JPanel panelDongHo;
	private javax.swing.JPanel panelManHinhChinh;
	// End of variables declaration//GEN-END:variables
}
