/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.DAO_Dondathang;
import dao.DAO_Khachhang;
import dao.DAO_Loaisanpham;
import dao.DAO_Sanpham;
import databaseconnect.ConnectDB;
import entity.ChiTietDonDatHang;
import entity.DonDatHang;
import entity.Khachhang;
import entity.LoaiSanPham;
import entity.NhanVien;
import entity.SanPham;
import entity.TrangThaiDonDat;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lenovo
 */
public class OrderFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	int donhangmoi = 0;
	DonDatHang dondathang;
	private static Khachhang khachhang;
	ChiTietDonDatHang chitietDondathang;
	int chucnang = 0;
	List<ChiTietDonDatHang> dsChitietdonhang;
	String manv=new LoginFrame().getMaNVText();
	public OrderFrame(Khachhang khachhang) throws ClassNotFoundException {
		initComponents();
		loadLoaisanpham();
		this.setLocationRelativeTo(null);
		disabled();
		OrderFrame.khachhang=khachhang;
		hienThiKhachHang();
	}

	private void hienThiKhachHang() {
		// TODO Auto-generated method stub
		txtDiaChi.setText(khachhang.getDiachi());
    	txtEmail.setText(khachhang.getEmail());
    	txtSDT.setText(khachhang.getSodienthoai());
    	txtTenKH.setText(khachhang.getTenKH());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNhapKH = new javax.swing.JPanel();
        labelTenKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        labelDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        labelSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelNgayDat = new javax.swing.JLabel();
        labelNgayGui = new javax.swing.JLabel();
        dateNgayGui = new com.toedter.calendar.JDateChooser();
        dateNgayDat = new com.toedter.calendar.JDateChooser();
        labelTrangThai = new javax.swing.JLabel();
        cbTrangThai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNoiNhan = new javax.swing.JTextField();
        btnThemDH = new javax.swing.JButton();
        btnSuaDH = new javax.swing.JButton();
        btnInDH = new javax.swing.JButton();
        btnLuuDonhang = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnXoaSP1 = new javax.swing.JButton();
        lblTongtien = new javax.swing.JLabel();
        valTongtien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSPDH = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();
        labelLoaiSP = new javax.swing.JLabel();
        cbLoaiSP = new javax.swing.JComboBox<>();
        labelSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemSP = new javax.swing.JButton();
        labelHinhAnh = new javax.swing.JLabel();
        labelSoluongton = new javax.swing.JLabel();
        jLabelMucgiam = new javax.swing.JLabel();
        txtMucGiam = new javax.swing.JTextField();
        labelDatHang = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelNhapKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenKH.setText("Tên khách hàng");

        labelDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDiaChi.setText("Địa chỉ");

        labelSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSDT.setText("Số điện thoại");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEmail.setText("Email");

        labelNgayDat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNgayDat.setText("Ngày đặt");

        labelNgayGui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNgayGui.setText("Ngày giao");

        dateNgayGui.setDateFormatString("dd/MM/yyyy");

        dateNgayDat.setDateFormatString("dd/MM/yyyy");

        labelTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTrangThai.setText("Trạng thái:");

        cbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Đã xác nhận", "Đang giao", "Thành công" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nơi nhận");

        javax.swing.GroupLayout panelNhapKHLayout = new javax.swing.GroupLayout(panelNhapKH);
        panelNhapKH.setLayout(panelNhapKHLayout);
        panelNhapKHLayout.setHorizontalGroup(
            panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhapKHLayout.createSequentialGroup()
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNhapKHLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNgayDat)
                            .addComponent(labelDiaChi)
                            .addComponent(labelTrangThai))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiaChi)
                            .addComponent(cbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                        .addComponent(labelTenKH)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenKH)))
                .addGap(73, 73, 73)
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                        .addComponent(labelSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                        .addComponent(labelNgayGui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgayGui, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        panelNhapKHLayout.setVerticalGroup(
            panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapKHLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenKH)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNgayGui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayGui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTrangThai)
                    .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbTrangThai, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNhapKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnThemDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemDH.setText("Đơn hàng");
        btnThemDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDHActionPerformed(evt);
            }
        });

        btnSuaDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSuaDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        btnSuaDH.setText("Sửa ");
        btnSuaDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDHActionPerformed(evt);
            }
        });

        btnInDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        btnInDH.setText("In đơn hàng");
        btnInDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnInDHActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnLuuDonhang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuuDonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnLuuDonhang.setText("Lưu đơn hàng");
        btnLuuDonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnLuuDonhangActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnXoaSP1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoaSP1.setText("Xóa");
        btnXoaSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSP1ActionPerformed(evt);
            }
        });

        lblTongtien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTongtien.setText("Tổng tiền đơn hàng: ");

        valTongtien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNhapKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSuaDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuuDonhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai)
                    .addComponent(btnXoaSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNhapKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuaDH)
                            .addComponent(btnXoaSP1))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInDH)
                            .addComponent(btnLuuDonhang)
                            .addComponent(btnQuayLai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnThemDH)
                        .addGap(19, 19, 19))))
        );

        tableSPDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Mức giảm giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSPDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					tableSPDHMouseClicked(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane1.setViewportView(tableSPDH);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					tableSPMouseClicked(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane3.setViewportView(tableSP);

        labelLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLoaiSP.setText("Loại sản phẩm");

        cbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLoaiSP.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                try {
					cbLoaiSPPopupMenuWillBecomeInvisible(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbLoaiSPMouseClicked(evt);
            }
        });

        labelSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSoLuong.setText("Số lượng");

        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        btnThemSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemSP.setText("Lưu");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnThemSPActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        labelHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHinhAnh.setText("Ảnh");
        labelHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelSoluongton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSoluongton.setForeground(new java.awt.Color(255, 0, 0));

        jLabelMucgiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMucgiam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMucgiam.setText("Mức giảm giá:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labelLoaiSP)
                                .addGap(18, 18, 18)
                                .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelSoLuong)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelSoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelMucgiam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLoaiSP)
                    .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSoLuong))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelSoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMucgiam)
                            .addComponent(txtMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(btnThemSP))
                    .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelDatHang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelDatHang.setText("Đặt hàng");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(489, 489, 489)
                        .addComponent(labelDatHang)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDatHang)
                    .addComponent(btnThoat))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
			new HomeFrame().setVisible(true);
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnThoatActionPerformed

	private void btnSuaDHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaDHActionPerformed
		// TODO add your handling code here:
		chucnang = 2;
		btnThemDH.setEnabled(false);
		txtSoLuong.setEnabled(true);
		btnThemSP.setEnabled(true);
		txtMucGiam.setEnabled(true);
	}// GEN-LAST:event_btnSuaDHActionPerformed

	private void btnLuuDonhangActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_btnLuuDonhangActionPerformed
		if (donhangmoi == 1) {
			if (kiemtratrong()) {
				khachhang = taoKhachhang();
				dondathang = taoDonhang(khachhang);
				if (kiemtratontaiKhachhang(khachhang)) {
					themdonhang(dondathang);
					dondathang.setMaDonDat(new DAO_Dondathang().getMadonhang());
					themChitietdonhang(dsChitietdonhang, dondathang);
				} else {
					insertKhachhang(khachhang);
					khachhang = getKhachhang(txtSDT.getText());
					dondathang.setKhachHang(khachhang);
					themdonhang(dondathang);
					dondathang.setMaDonDat(new DAO_Dondathang().getMadonhang());
					themChitietdonhang(dsChitietdonhang, dondathang);
				}
				capnhatTongtien(dondathang.getTongTien());
				capnhatSoluongton();
				System.out.println(dondathang.getTongTien());
				JOptionPane.showMessageDialog(this,
						"Đặt hàng thành công!\nMã đơn hàng của bạn là: " + new DAO_Dondathang().getMadonhang());
				disabled();
//				clearText();
				btnInDH.setEnabled(true);
			}
		}
	}// GEN-LAST:event_btnLuuDonhangActionPerformed

	private void btnInDHActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_btnInDHActionPerformed
		// TODO add your handling code here:
        Connection con = ConnectDB.getConnection();
    	try {
		JasperDesign jd =  JRXmlLoader.load("src\\hoadon\\donhang.jrxml");
    	JasperReport report = JasperCompileManager.compileReport("src\\hoadon\\donhang.jrxml");
	    	JasperPrint jp = JasperFillManager.fillReport(report, new HashMap(), con);
	    	JasperViewer.viewReport(jp);
		} catch (JRException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnInDHActionPerformed

	private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuayLaiActionPerformed
		// TODO add your handling code here:
		clearText();
		disabled();
		btnThemDH.setEnabled(true);
	}// GEN-LAST:event_btnQuayLaiActionPerformed

	private void btnThemDHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemDHActionPerformed
		// TODO add your handling code here:
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm đơn hàng mới?", "Hỏi nhắc",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			enebled();
			khachhang = new Khachhang();
			dondathang = new DonDatHang();
			dsChitietdonhang = new ArrayList<ChiTietDonDatHang>();
			donhangmoi = 1;
			chucnang = 1;
			btnInDH.setEnabled(false);
			txtMucGiam.setEnabled(false);
		}
	}// GEN-LAST:event_btnThemDHActionPerformed

	private void btnXoaSP1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaSP1ActionPerformed
		// TODO add your handling code here:
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sản phẩm này khỏi đơn hàng?", "Hỏi nhắc",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			xoaSanpham(dsChitietdonhang);
			btnXoaSP1.setEnabled(false);
			btnSuaDH.setEnabled(false);
		}
	}// GEN-LAST:event_btnXoaSP1ActionPerformed

	private void cbLoaiSPPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_cbLoaiSPPopupMenuWillBecomeInvisible
		// TODO add your handling code here:
		loadSanpham(cbLoaiSP.getSelectedItem().toString());
		btnThemSP.setEnabled(false);
		txtSoLuong.setText("");
		txtSoLuong.setEnabled(false);
		labelSoluongton.setText("");
		chucnang = 1;
	}// GEN-LAST:event_cbLoaiSPPopupMenuWillBecomeInvisible

	private void tableSPMouseClicked(java.awt.event.MouseEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_tableSPMouseClicked
		// TODO add your handling code here:
		hienthiHinhanh(tableSP.getValueAt(tableSP.getSelectedRow(), 0).toString());
		btnThemSP.setEnabled(true);
		int soluongton = getSoluongton(tableSP.getValueAt(tableSP.getSelectedRow(), 1).toString());
		labelSoluongton.setText("Số lượng tồn: " + soluongton);
		txtSoLuong.setEnabled(true);
		txtMucGiam.setEnabled(true);
	}// GEN-LAST:event_tableSPMouseClicked

	private void cbLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cbLoaiSPMouseClicked
		// TODO add your handling code here:

	}// GEN-LAST:event_cbLoaiSPMouseClicked

	private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_btnThemSPActionPerformed
		// TODO add your handling code here:
		
		if (txtSoLuong.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng cho sản phẩm!");
		} else {
			if(kiemtraSoluong(Integer.parseInt(txtSoLuong.getText()), getSoluongton(tableSP.getValueAt(tableSP.getSelectedRow(), 1).toString()))) {
				if (chucnang == 1) {
					SanPham sanpham = new DAO_Sanpham()
							.getSanphamByName(tableSP.getValueAt(tableSP.getSelectedRow(), 1).toString());
					chitietDondathang = taoChitietDonhang(dondathang, sanpham);
					if (kiemtratrungSanpham(chitietDondathang)) {
						dsChitietdonhang.add(chitietDondathang);
						dondathang.addChitietdonhang(dondathang, sanpham, chitietDondathang.getSoluong(),
								chitietDondathang.getDongia(),chitietDondathang.getMucGiamGia());
						docbangDonhang();
					}
				} else if (chucnang == 2) {
					String maSua = tableSPDH.getValueAt(tableSPDH.getSelectedRow(), 0).toString();
					for (int i = 0; i < dsChitietdonhang.size(); i++) {
						if (dsChitietdonhang.get(i).getSanpham().getMaSP().equals( maSua)) {
							dsChitietdonhang.get(i).setSoluong(Integer.parseInt(txtSoLuong.getText()));
							dsChitietdonhang.get(i).setMucGiamGia(Double.parseDouble(txtMucGiam.getText()) );
							dondathang.updateChitietdonhang(i, Integer.parseInt(txtSoLuong.getText()),Double.parseDouble(txtMucGiam.getText()));
						}
					}
					docbangDonhang();
				}
			}
			valTongtien.setText(formatMoney(dondathang.getTongTien()) + " VND");
			txtSoLuong.setText("");
			txtSoLuong.setEnabled(false);
			btnThemSP.setEnabled(false);
			txtMucGiam.setEnabled(false);

		}
	}// GEN-LAST:event_btnThemSPActionPerformed

	private void tableSPDHMouseClicked(java.awt.event.MouseEvent evt) throws ClassNotFoundException {// GEN-FIRST:event_tableSPDHMouseClicked
		// TODO add your handling code here:
		DAO_Sanpham dao_Sanpham = new DAO_Sanpham();
		int click = tableSPDH.getSelectedRow();
		TableModel tableModel = tableSPDH.getModel();
		List<SanPham> dsSp = dao_Sanpham.getSanPham(tableModel.getValueAt(click, 1).toString());
		for (SanPham sanpham : dsSp) {
			cbLoaiSP.setSelectedItem(sanpham.getMaLoaiSP().getTenLoaiSP());
//		    	loadSanpham(cbLoaiSP.getSelectedItem().toString());
		}
//	    	loadSanpham(cbLoaiSP.getSelectedItem().toString());
		SanPham sanpham = dao_Sanpham.getSanphamByName(tableModel.getValueAt(click, 1).toString());
		Object[] tableModel1 = { sanpham.getMaSP(), sanpham.getTenSP(), sanpham.getDonGia() };
		DefaultTableModel modelSanpham = new DefaultTableModel(
				new Object[] { "Mã sản phẩm", "Tên sản phẩm", "Đơn giá" }, 0);
		modelSanpham.addRow(tableModel1);
		tableSP.setModel(modelSanpham);

		hienthiHinhanh(tableModel.getValueAt(click, 0).toString());
		tableSP.setRowSelectionInterval(0, 0);
		btnXoaSP1.setEnabled(true);
		btnSuaDH.setEnabled(true);
		
		txtSoLuong.setText(tableModel.getValueAt(click, 2).toString());
	}// GEN-LAST:event_tableSPDHMouseClicked

	private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtSoLuongKeyReleased
		// TODO add your handling code here:
		btnThemSP.setEnabled(true);
	}// GEN-LAST:event_txtSoLuongKeyReleased

	/**
	 * @param args the command line arguments
	 */
	
	public boolean kiemtraSoluong(int soluong, int soluongton) {
		if(soluong > soluongton) {
			JOptionPane.showMessageDialog(this, "Sản phẩm không đủ số lượng!", "Cảnh báo", JOptionPane.CLOSED_OPTION);
			return false;
		}
		return true;
	}
	private String formatMoney(double tien) {
		String matter;
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		matter = formatter.format(tien);
		return matter;
	}

	private boolean kiemtratrungSanpham(ChiTietDonDatHang cthd) {
		for (int i = 0; i < dsChitietdonhang.size(); i++) {
			if (dsChitietdonhang.get(i).getSanpham().getTenSP().equals(cthd.getSanpham().getTenSP())) {
				JOptionPane.showMessageDialog(this, "Sản phẩm đã có trong hóa đơn!");
				return false;
			}
		}
		return true;
	}

	private boolean kiemtratrong() {
		if (txtDiaChi.getText().equals("") || txtEmail.getText().equals("") || txtSDT.getText().equals("")
				|| txtTenKH.getText().equals("") || dsChitietdonhang.size() == 0) {
			JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin!");
			return false;
		}else if(dateNgayDat.getDate().getTime()>=dateNgayGui.getDate().getTime()) {
			JOptionPane.showMessageDialog(this, "Ngày đặt không được lớn hơn hoặc bằng ngày gửi!");
			return false;
		}
		return true;
	}

	private void xoaSanpham(List<ChiTietDonDatHang> dsChitietdh) {
		int click = tableSPDH.getSelectedRow();
		String tenspXoa = tableSPDH.getValueAt(click, 1).toString();
		for (int i = 0; i < dsChitietdh.size(); i++) {
			if (dsChitietdh.get(i).getSanpham().getTenSP().equals(tenspXoa)) {
				dsChitietdh.remove(i);
				dondathang.removeChitietdonhang(i);
				valTongtien.setText(dondathang.getTongTien() + "");
			}
		}
		docbangDonhang();
	}

	private void clearText() {
		txtTenKH.setText("");
		DefaultTableModel modelDathang = new DefaultTableModel(
				new Object[] { "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền" }, 0);
		tableSPDH.setModel(modelDathang);
		DefaultTableModel modelSanpham = new DefaultTableModel(
				new Object[] { "Mã sản phẩm", "Tên sản phẩm", "Đơn giá" }, 0);
		tableSP.setModel(modelSanpham);
		valTongtien.setText("");
		labelSoluongton.setText("");
	}

	private void capnhatSoluongton() throws ClassNotFoundException {
		DAO_Sanpham dao_sanpham = new DAO_Sanpham();
		int row = 0;
		int colSoluong = 2;
		int colTensp = 1;
		for (int i = row; i < tableSPDH.getRowCount(); i++) {
			String tensp = tableSPDH.getValueAt(i, colTensp).toString();
			int soluongton = dao_sanpham.getSoluongton(tensp);
			int soluongmua = Integer.parseInt(tableSPDH.getValueAt(row, colSoluong).toString());
			int soluongtonmoi = soluongton - soluongmua;
			if (dao_sanpham.updateSoluongton(tensp, soluongtonmoi))
				;
			row++;
		}
	}

	private int getSoluongton(String tensp) throws ClassNotFoundException {
		return new DAO_Sanpham().getSoluongton(tensp);
	}

	private boolean capnhatTongtien(double tongtien) throws ClassNotFoundException {
		DAO_Dondathang dao_Dondathang = new DAO_Dondathang();
		return dao_Dondathang.capnhatTongtien(tongtien);
	}

	private void loadLoaisanpham() throws ClassNotFoundException {
		
		cbLoaiSP.removeAllItems();
		try {
			List<LoaiSanPham> dsLoaisp = new DAO_Loaisanpham().getLoaiSanPham();
			for (LoaiSanPham loaiSP : dsLoaisp) {
				cbLoaiSP.addItem(loaiSP.getTenLoaiSP());
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void loadSanpham(String loaisanpham) throws ClassNotFoundException {
		List<SanPham> dsSanpham = new DAO_Loaisanpham().getSanpham(loaisanpham);
		DefaultTableModel model = new DefaultTableModel(new Object[] { "Mã sản phẩm", "Tên sản phẩm", "Đơn giá" }, 0);
		for (SanPham sanpham : dsSanpham) {
			Object[] tableModel = { sanpham.getMaSP(), sanpham.getTenSP(), sanpham.getDonGia() };
			model.addRow(tableModel);
		}
		tableSP.setModel(model);

	}

	private void hienthiHinhanh(String maSp) throws ClassNotFoundException {
		try {
			String path = new DAO_Sanpham().getImg(maSp);
			ImageIcon icon = new ImageIcon(path);
			Image img = icon.getImage();
			Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(), Image.SCALE_SMOOTH);
			ImageIcon imgIcon = new ImageIcon(newImg);
			labelHinhAnh.setIcon(imgIcon);
		} catch (SQLException | IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void disabled() {
		txtDiaChi.setEnabled(false);
		txtEmail.setEnabled(false);
		txtSDT.setEnabled(false);
		txtSoLuong.setEnabled(false);
		txtTenKH.setEnabled(false);
		btnInDH.setEnabled(false);
		btnSuaDH.setEnabled(false);
		btnXoaSP1.setEnabled(false);
		btnLuuDonhang.setEnabled(false);
		btnThemSP.setEnabled(false);
		dateNgayDat.setEnabled(false);
		dateNgayGui.setEnabled(false);
		cbTrangThai.setEnabled(false);
		cbLoaiSP.setEnabled(false);
		txtMucGiam.setEnabled(false);
		txtNoiNhan.setEnabled(false);
		btnQuayLai.setEnabled(false);
	}

	private void enebled() {
		btnLuuDonhang.setEnabled(true);
		dateNgayDat.setEnabled(true);
		dateNgayGui.setEnabled(true);
		cbTrangThai.setEnabled(true);
		cbLoaiSP.setEnabled(true);
		txtMucGiam.setEnabled(true);
		txtNoiNhan.setEnabled(true);
		btnQuayLai.setEnabled(true);
	}

	private Khachhang taoKhachhang() {
		Khachhang khachhang = new Khachhang();
		khachhang.setDiachi(txtDiaChi.getText());
		khachhang.setEmail(txtEmail.getText());
		khachhang.setSodienthoai(txtSDT.getText());
		khachhang.setTenKH(txtTenKH.getText());
		return khachhang;
	}

	private DonDatHang taoDonhang(Khachhang khachhang) throws ClassNotFoundException {
		TrangThaiDonDat trangthai = new DAO_Dondathang().getTrangthai(cbTrangThai.getSelectedItem().toString());
		dondathang.setKhachHang(khachhang);
		dondathang.setNgaydat(new java.sql.Date(dateNgayDat.getDate().getTime()));
		dondathang.setNgaygiao(new java.sql.Date(dateNgayGui.getDate().getTime()));
		dondathang.setNhanvien(new NhanVien(manv));
		dondathang.setNoiNhan(txtNoiNhan.getText());
		dondathang.setTrangThaiDonDat(trangthai);
		return dondathang;
	}

	private ChiTietDonDatHang taoChitietDonhang(DonDatHang donhang, SanPham sanpham) {
		ChiTietDonDatHang ctdonhang = new ChiTietDonDatHang();
		ctdonhang.setDondathang(donhang);
		ctdonhang.setDongia(sanpham.getDonGia());
		ctdonhang.setSanpham(sanpham);
		ctdonhang.setSoluong(Integer.parseInt(txtSoLuong.getText()));
		ctdonhang.setMucGiamGia(Double.parseDouble(txtMucGiam.getText()));
//    	System.out.println(ctdonhang.getDongia()+","+ctdonhang.getSoluong());
		return ctdonhang;
	}

	private void docbangDonhang() {
		DefaultTableModel model = new DefaultTableModel(
				new Object[] { "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá","Mức giảm giá", "Thành tiền" }, 0);
		for (ChiTietDonDatHang ctdh : dsChitietdonhang) {
			double thanhtien = (ctdh.getSoluong() * ctdh.getDongia())-ctdh.getMucGiamGia();
			Object[] tableModel = { ctdh.getSanpham().getMaSP(), ctdh.getSanpham().getTenSP(),
					ctdh.getSoluong(), ctdh.getDongia(),ctdh.getMucGiamGia(), thanhtien };
			model.addRow(tableModel);
		}
		tableSPDH.setModel(model);
	}

	private boolean kiemtratontaiKhachhang(Khachhang khachhang) throws ClassNotFoundException {
		DAO_Khachhang dao_khachang = new DAO_Khachhang();
		List<Khachhang> dsKhachang = dao_khachang.kiemtratontaiKhachhang(khachhang);
		if (dsKhachang.size() != 0)
			return true;
		else
			return false;
	}

	private void themdonhang(DonDatHang donhang) throws ClassNotFoundException {
		DAO_Dondathang dao_Dondathang = new DAO_Dondathang();
		dao_Dondathang.insertDonhang(donhang);
	}

	private void themChitietdonhang(List<ChiTietDonDatHang> dsChitietdonhang, DonDatHang donhang) throws ClassNotFoundException {
		DAO_Dondathang dao_Dondathang = new DAO_Dondathang();
		for (ChiTietDonDatHang ctdh : dsChitietdonhang) {
			ctdh.setDondathang(donhang);
			dao_Dondathang.themSanphamvaoCTHD(ctdh);
		}
	}

	private void insertKhachhang(Khachhang khachhang) {
		DAO_Khachhang dao_khachhang = new DAO_Khachhang();
		try {
			dao_khachhang.insertKhachhang(khachhang);
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private Khachhang getKhachhang(String sodienthoai) throws ClassNotFoundException {
		DAO_Khachhang dao_Khachhang = new DAO_Khachhang();
		Khachhang kh = dao_Khachhang.getKhachhang(sodienthoai);
		return kh;
	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new OrderFrame(khachhang).setVisible(true);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInDH;
    private javax.swing.JButton btnLuuDonhang;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSuaDH;
    private javax.swing.JButton btnThemDH;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaSP1;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JComboBox<String> cbTrangThai;
    private com.toedter.calendar.JDateChooser dateNgayDat;
    private com.toedter.calendar.JDateChooser dateNgayGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMucgiam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDatHang;
    private javax.swing.JLabel labelDiaChi;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JLabel labelLoaiSP;
    private javax.swing.JLabel labelNgayDat;
    private javax.swing.JLabel labelNgayGui;
    private javax.swing.JLabel labelSDT;
    private javax.swing.JLabel labelSoLuong;
    private javax.swing.JLabel labelSoluongton;
    private javax.swing.JLabel labelTenKH;
    private javax.swing.JLabel labelTrangThai;
    private javax.swing.JLabel lblTongtien;
    private javax.swing.JPanel panelNhapKH;
    private javax.swing.JTable tableSP;
    private javax.swing.JTable tableSPDH;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMucGiam;
    private javax.swing.JTextField txtNoiNhan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JLabel valTongtien;
    // End of variables declaration//GEN-END:variables
}
