/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.DAO_Loaisanpham;
import dao.DAO_Sanpham;
import entity.LoaiSanPham;
import entity.NhaCungCap;
import entity.SanPham;

/**
 *
 * @author Lenovo
 */
public class ProductFrame extends javax.swing.JFrame implements ItemListener {

    /**
     * Creates new form NewJFrame2
     */
	int chucnang = 0;
    private String path = "";
    public ProductFrame() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        showProductTable();
        disabled();
        try {
			loadCbLoaiSp();
			loadCbNhacungcap();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuanLySP = new javax.swing.JPanel();
        labelQLSP = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThoat = new javax.swing.JButton();
        labelHinhAnh = new javax.swing.JLabel();
        labelMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        labelTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        labelDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        labelSoLuongTon = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        labelTrangThai = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        labelMaNCC = new javax.swing.JLabel();
        cbMaNCC = new javax.swing.JComboBox<>();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTenSPTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        labelTenSPTimKiem = new javax.swing.JLabel();
        labelLoaiSP = new javax.swing.JLabel();
        cbLoaiSP = new javax.swing.JComboBox<>();
        btnChonanh = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelQuanLySP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelQLSP.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelQLSP.setText("QUẢN LÝ SẢN PHẨM");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnThoatActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        labelHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHinhAnh.setText("Ảnh");
        labelHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelMaSP.setText("Mã sản phẩm");

        labelTenSP.setText("Tên sản phẩm");

        labelDonGia.setText("Đơn giá");

        labelSoLuongTon.setText("Sô lượng tồn");

        labelTrangThai.setText("Trạng thái");

        labelMaNCC.setText("Mã nhà cung cấp");

        cbMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnXoaActionPerformed(evt);
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnLuu.setText("Lưiu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnLuuActionPerformed(evt);
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnReset.setText("Quay lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnTimActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        labelTenSPTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTenSPTimKiem.setText("Tên Sản Phẩm");

        labelLoaiSP.setText("Loại sản phẩm");

        cbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChonanh.setText("Chọn ảnh");
        btnChonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonanhActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLySPLayout = new javax.swing.GroupLayout(panelQuanLySP);
        panelQuanLySP.setLayout(panelQuanLySPLayout);
        panelQuanLySPLayout.setHorizontalGroup(
            panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelQuanLySPLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(labelLoaiSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(labelDonGia)
                        .addGap(18, 18, 18)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(labelMaNCC)
                        .addGap(18, 18, 18)
                        .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addGap(18, 18, 18)
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addComponent(labelMaSP)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addComponent(labelSoLuongTon)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                    .addComponent(labelTenSP)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                    .addComponent(labelTrangThai)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(labelTenSPTimKiem)))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(txtTenSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))))
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnThoat)
                        .addGap(310, 310, 310)
                        .addComponent(labelQLSP))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnChonanh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelQuanLySPLayout.setVerticalGroup(
            panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat)
                    .addComponent(labelQLSP))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(labelMaSP)
                            .addComponent(txtMaSP)
                            .addComponent(labelTenSP)
                            .addComponent(txtTenSP)
                            .addComponent(labelLoaiSP)
                            .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDonGia)
                            .addComponent(txtDonGia)
                            .addComponent(labelSoLuongTon)
                            .addComponent(txtSoLuongTon)
                            .addComponent(labelTrangThai)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaNCC)
                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnChonanh)
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnTim))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(labelTenSPTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnLuu)
                    .addComponent(btnReset)
                    .addComponent(btnXoa)
                    .addComponent(btnThem))
                .addContainerGap())
        );

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng tồn", "Trạng ", "Mã nhà sản xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					tableSPMouseClicked(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane1.setViewportView(tableSP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelQuanLySP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelQuanLySP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        cbLoaiSP.addItemListener(this);
        cbMaNCC.addItemListener(this);
    }// </editor-fold>//GEN-END:initComponents

    private void tableSPMouseClicked(java.awt.event.MouseEvent evt) throws ClassNotFoundException {//GEN-FIRST:event_tableSPMouseClicked
        // TODO add your handling code here:
    	int click = tableSP.getSelectedRow();
		TableModel tableModel = tableSP.getModel();
		cbLoaiSP.setSelectedItem(tableModel.getValueAt(click, 4).toString());
		txtMaSP.setText(tableModel.getValueAt(click, 0).toString());
		txtTenSP.setText(tableModel.getValueAt(click, 1).toString());
		txtDonGia.setText(tableModel.getValueAt(click, 3).toString());
		txtSoLuongTon.setText(tableModel.getValueAt(click, 2).toString());
		if(Integer.parseInt(tableModel.getValueAt(click, 2).toString()) > 0){
			txtTrangThai.setText("Còn hàng");
		}else
			txtTrangThai.setText("Hết hàng");
		cbMaNCC.setSelectedItem(tableModel.getValueAt(click,5).toString());
		btnSua.setEnabled(true);
		btnXoa.setEnabled(true);
		DAO_Sanpham dao_sanpham = new DAO_Sanpham();
		try {
			
			path = dao_sanpham.getImg(tableModel.getValueAt(click, 0).toString());
			ImageIcon icon = new ImageIcon(path);
			Image img = icon.getImage();
			Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(), Image.SCALE_SMOOTH);
			ImageIcon imgIcon = new ImageIcon(newImg);
			labelHinhAnh.setIcon(imgIcon);
		
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_tableSPMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm sản phẩm mới", "Hỏi nhắc", JOptionPane.YES_NO_CANCEL_OPTION);
        if(yes == JOptionPane.YES_OPTION) {
            enabled();
            btnLuu.setEnabled(true);
            chucnang = 1;
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnChonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonanhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.setDialogTitle("Chọn ảnh");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image","jpg", "png");
        chooser.addChoosableFileFilter(filter);

        int result = chooser.showSaveDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getName();
        if(filename.endsWith(".jpg")||filename.endsWith(".JPG")||filename.endsWith(".png")||filename.endsWith(".PNG")){
            if(result == JFileChooser.APPROVE_OPTION){
                path = file.getAbsolutePath();
                ImageIcon imgIcon = new ImageIcon(path);
                Image img = imgIcon.getImage();

                Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(), Image.SCALE_SMOOTH);

                ImageIcon icon = new ImageIcon(newImg);
                labelHinhAnh.setIcon(icon);

            }
        }else
        JOptionPane.showMessageDialog(this,"Chọn sai tệp, vui lòng chọn tệp hình ảnh");

    }//GEN-LAST:event_btnChonanhActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {//GEN-FIRST:event_btnTimActionPerformed
    	String tukhoa = txtTenSPTimKiem.getText();
    	DefaultTableModel model = new DefaultTableModel(new Object[]{"Mã sản phẩm", "Tên sản phẩm", "Số lượng tồn", "Đơn giá","Loại sản phẩm","Nhà cung cấp"}, 0);
    	
    	List<SanPham> dsDungcu= new DAO_Sanpham().getSanPham(tukhoa);
    	for(SanPham sanpham :dsDungcu) {
    		Object[] tableModel = {sanpham.getMaSP(), sanpham.getTenSP(), sanpham.getSlton(), 
    				sanpham.getDonGia(), sanpham.getMaNCC().getMaNCC(),sanpham.getMaLoaiSP().getMaLoaiSP()};
    		model.addRow(tableModel);
    	}
    	tableSP.setModel(model);
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    	refesh();
    	disabled();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, ClassNotFoundException {//GEN-FIRST:event_btnLuuActionPerformed
        if(chucnang==1) {
            try {
                insertSanpham();
                path = "";
                refesh();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }else if(chucnang == 2) {
        	int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật sản phẩm này", "Hỏi nhắc", JOptionPane.YES_NO_CANCEL_OPTION);
            if(yes == JOptionPane.YES_OPTION) {
            	try {
					updateSanpham();
					refesh();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    	enabled();
    	btnLuu.setEnabled(true);
    	btnThem.setEnabled(false);
    	btnXoa.setEnabled(false);
    	chucnang=2;
    	
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {//GEN-FIRST:event_btnThoatActionPerformed
        dispose();
        new HomeFrame().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, ClassNotFoundException {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    	try {
			deleteSanpham(txtMaSP.getText().trim());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     * @throws ClassNotFoundException 
     * @throws HeadlessException 
     */
    private void updateSanpham() throws SQLException, HeadlessException, ClassNotFoundException {
    	DAO_Sanpham dao_sanpham = new DAO_Sanpham();
    	String mancc = null,maloai = null;
    	String tenLoaiSP = cbLoaiSP.getSelectedItem().toString();
    	String tenNhaCC = cbMaNCC.getSelectedItem().toString();  	
    	List<LoaiSanPham> dsLoaiSp = new DAO_Loaisanpham().getLoaiSanPham();
    	for(LoaiSanPham loaisp : dsLoaiSp) {
    		if(loaisp.getTenLoaiSP().equals(tenLoaiSP)) {
    			maloai=loaisp.getMaLoaiSP();
    		}
    		
    	}

    	List<NhaCungCap> dsNhacc = dao_sanpham.getNhacungcap();
    	for(NhaCungCap nhacc : dsNhacc) {
    		if(nhacc.getTenNCC().equals(tenNhaCC)) {
    			mancc=nhacc.getMaNCC();
    		}
    	}
    	if(Integer.parseInt(txtSoLuongTon.getText().trim()) >0) {
    		txtTrangThai.setText("Còn hàng");
    	}else {
    		txtTrangThai.setText("Hết hàng");
    	}
    	String masp=txtMaSP.getText().trim();
    	String tensp=txtTenSP.getText().trim();
    	Double dongia=Double.parseDouble(txtDonGia.getText().trim());
    	int slton=Integer.parseInt(txtSoLuongTon.getText().trim());
    	SanPham sp=new SanPham(masp, tensp, slton, dongia,null, null);
    	if(dao_sanpham.updateSanpham(sp, path,maloai,mancc)) {
    		JOptionPane.showMessageDialog(this, "Cập nhật Sản phẩm thành công!");
    		showProductTable();
    	}
    	else {
    		JOptionPane.showMessageDialog(this, "Cập nhật Sản phẩm thất bại, Hãy thử lại!");
    	}
    }
    private void deleteSanpham(String id) throws SQLException, HeadlessException, ClassNotFoundException {
    	DAO_Sanpham dao_sanpham = new DAO_Sanpham();
    	int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Sản phẩm này?", "Cảnh báo", JOptionPane.YES_NO_CANCEL_OPTION);

    	if(yes == JOptionPane.YES_OPTION) {
    		if(dao_sanpham.deleteSanpham(id)) {
    			JOptionPane.showMessageDialog(this, "Sản phẩm đã được xóa");
    			
    		}else
    			JOptionPane.showMessageDialog(this, "Xoá không thành công, Vui lòng kiếm tra lại");
    	}
    	showProductTable();
    	disabled();
    }
    private void insertSanpham() throws SQLException, HeadlessException, ClassNotFoundException {

    	DAO_Sanpham dao_sanpham = new DAO_Sanpham();

    	String tenLoaiSP = cbLoaiSP.getSelectedItem().toString();
    	String tenNhaCC = cbMaNCC.getSelectedItem().toString();
    	SanPham sanpham = new SanPham();
    	List<LoaiSanPham> dsLoaiSp = new DAO_Loaisanpham().getLoaiSanPham();
    	for(LoaiSanPham loaisp : dsLoaiSp) {
    		if(loaisp.getTenLoaiSP().equals(tenLoaiSP)) {
    			sanpham.setMaLoaiSP(new LoaiSanPham(loaisp.getMaLoaiSP(),loaisp.getTenLoaiSP()));
    		}
    		
    	}
    	List<NhaCungCap> dsNhacc = dao_sanpham.getNhacungcap();
    	for(NhaCungCap nhacc : dsNhacc) {
    		if(nhacc.getTenNCC().equals(tenNhaCC)) {
    			sanpham.setMaNCC(new NhaCungCap(nhacc.getMaNCC(),nhacc.getTenNCC(),nhacc.getDiachi(),nhacc.getSdt()));
    		}
    	}
    	if(Integer.parseInt(txtSoLuongTon.getText().trim()) >0) {
    		txtTrangThai.setText("Còn hàng");
    	}else {
    		txtTrangThai.setText("Hết hàng");
    	}
    	sanpham.setTenSP(txtTenSP.getText().trim());
    	sanpham.setDonGia(Double.parseDouble(txtDonGia.getText().trim()));
    	sanpham.setSlton(Integer.parseInt(txtSoLuongTon.getText().trim()));
    	sanpham.setMaSP(txtMaSP.getText().trim());
    	if(dao_sanpham.insertSanpham(sanpham, path)) {
    		JOptionPane.showMessageDialog(this, "Thêm thành công!!");
    		showProductTable();
    	}else {
    		JOptionPane.showMessageDialog(this, "Thêm không thành công! Hãy thử lại");
    	}

    }
    private void disabled(){
    	txtDonGia.setEnabled(false);
    	txtMaSP.setEnabled(false);
    	txtSoLuongTon.setEnabled(false);
    	txtTenSP.setEnabled(false);
    	txtTrangThai.setEnabled(false);
    	btnLuu.setEnabled(false);
    	btnSua.setEnabled(false);
    	btnChonanh.setEnabled(false);
    	btnXoa.setEnabled(false);
    	cbLoaiSP.setEnabled(false);
    	cbMaNCC.setEnabled(false);
    }
    private void enabled(){
    	txtDonGia.setEnabled(true);
    	txtMaSP.setEnabled(true);
    	txtSoLuongTon.setEnabled(true);
    	txtTenSP.setEnabled(true);
    	txtTenSPTimKiem.setEnabled(true);
    	btnChonanh.setEnabled(true);
    	cbLoaiSP.setEnabled(true);
    	cbMaNCC.setEnabled(true);
    }
    private void refesh()  {
    	disabled();
    	btnThem.setEnabled(true);
        txtDonGia.setText("");
        txtMaSP.setText("");
        txtSoLuongTon.setText("");
        txtSoLuongTon.setText("");
        txtTenSP.setText("");
        txtTenSPTimKiem.setText("");
        txtTrangThai.setText("");
        cbLoaiSP.setSelectedIndex(0);
        cbMaNCC.setSelectedIndex(0);
        labelHinhAnh.setIcon(null);
        try {
			showProductTable();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    private void showProductTable() throws ClassNotFoundException {
        DefaultTableModel model = new DefaultTableModel(new Object[]{ "Mã sản phẩm", "Tên sản phẩm", "Số lượng tồn", "Đơn giá","Nhà cung cấp","Loại sản phẩm" }, 0);
    	DAO_Sanpham dao_sanpham = new DAO_Sanpham();
    	List<SanPham> list = dao_sanpham.getSanPham("");
    	if(list.size()==0) {
    		JOptionPane.showMessageDialog(this,"Không tìm thấy sản phẩm, Vui lòng thử lại");
    	}else {
        	for(SanPham sanpham : list) {
        		
        		Object[] tableModel = {sanpham.getMaSP(), sanpham.getTenSP(), sanpham.getSlton(), 
        				sanpham.getDonGia(), sanpham.getMaNCC().getTenNCC(),sanpham.getMaLoaiSP().getTenLoaiSP()};
        		model.addRow(tableModel);
        	}
        	tableSP.setModel(model);
    	}

    }
    private void loadCbLoaiSp() throws SQLException, ClassNotFoundException {
    	DAO_Loaisanpham dao_Loaisanpham = new DAO_Loaisanpham();
    	cbLoaiSP.removeAllItems();
    	List<LoaiSanPham> loaisp = dao_Loaisanpham.getLoaiSanPham();
    	for(LoaiSanPham lsp : loaisp) {
    		cbLoaiSP.addItem(lsp.getTenLoaiSP());
    	}
    }
    private void loadCbNhacungcap() throws SQLException, ClassNotFoundException {
    	DAO_Sanpham dao_sanpham = new DAO_Sanpham();
    	cbMaNCC.removeAllItems();
    	List<NhaCungCap> dsNhacungcap = dao_sanpham.getNhacungcap();
    	for(NhaCungCap nhacungcap : dsNhacungcap) {
    		cbMaNCC.addItem(nhacungcap.getTenNCC());
    	}
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
						javax.swing.UIManager.setLookAndFeel(info.getClassName());
					} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
							| UnsupportedLookAndFeelException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
                    break;
                }
            }
        } finally {
			
		}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new ProductFrame().setVisible(true);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonanh;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JComboBox<String> cbMaNCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDonGia;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JLabel labelLoaiSP;
    private javax.swing.JLabel labelMaNCC;
    private javax.swing.JLabel labelMaSP;
    private javax.swing.JLabel labelQLSP;
    private javax.swing.JLabel labelSoLuongTon;
    private javax.swing.JLabel labelTenSP;
    private javax.swing.JLabel labelTenSPTimKiem;
    private javax.swing.JLabel labelTrangThai;
    private javax.swing.JPanel panelQuanLySP;
    private javax.swing.JTable tableSP;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSPTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
	@Override
	public void itemStateChanged(ItemEvent e) {
		// TODO Auto-generated method stub
	}
}
